"""hotfix

Revision ID: 0fda27e37bfc
Revises: 654f1d97ff8d
Create Date: 2024-12-07 23:09:44.758089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fda27e37bfc'
down_revision: Union[str, None] = '654f1d97ff8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codes', 'orders', ['order_id'], ['id'])
    op.drop_column('codes', 'order_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.drop_column('codes', 'order_id')
    # ### end Alembic commands ###
